---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: transformer
  namespace: minio-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transformer
  template:
    metadata:
      labels:
        app: transformer
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: minio-webhook-data
        - name: transformer-tls
          secret:
            secretName: transformer-tls
      containers:
        - resources:
            limits:
              cpu: 250m
              memory: 200Mi
            requests:
              cpu: 20m
              memory: 100Mi
          readinessProbe:
            tcpSocket:
              port: 8443
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: transformer
          livenessProbe:
            tcpSocket:
              port: 8443
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: MINIO_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: minio-webhook-config
                  key: minioEndpoint
            - name: MINIO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: username
            - name: MINIO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: password
            - name: MINIO_BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: minio-webhook-config
                  key: bucketName
            - name: TLS_SECRET_NAME
              value: transformer-tls
          ports:
            - containerPort: 8443
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: data
              mountPath: /data
            - name: transformer-tls
              mountPath: /var/run/secrets/transformer-tls
              readOnly: true
          terminationMessagePolicy: File
          image: >-
            quay.io/fdupont-redhat/minio-webhook:latest
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - |
                    /usr/bin/python3.12 /app/minio_webhook_enable.py > /data/enable.log 2>&1
            preStop:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - |
                    /usr/bin/python3.12 /app/minio_webhook_disable.py > /data/disable.log 2>&1
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
