---
kind: Service
apiVersion: v1
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: transformer-tls
  name: transformer
  namespace: minio-webhook
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: hook
      protocol: TCP
      port: 8443
      targetPort: 8443
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: transformer
