---
kind: Service
apiVersion: v1
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: input-infer-tls
  name: input-infer
  namespace: minio-webhooks
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: hook
      protocol: TCP
      port: 8443
      targetPort: 8443
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: input-infer
