---
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  annotations:
    openshift.io/display-name: yolo
    serving.kserve.io/deploymentMode: RawDeployment
  labels:
    opendatahub.io/dashboard: 'true'
  name: yolo-no-transformer
  namespace: edge-ai-app
spec:
  predictor:
    maxReplicas: 1
    minReplicas: 1
    serviceAccountName: yolo
    model:
      modelFormat:
        name: onnx
        version: '1'
      resources:
        limits:
          cpu: '2'
          memory: 4Gi
        requests:
          cpu: '1'
          memory: 2Gi
      runtime: yolo-transformer
      storageUri: 's3://models/yolo'
