---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: transformer-data
  namespace: edge-ai-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
