---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    serving.kserve.io/s3-endpoint: "minio.minio.svc:9000"
    serving.kserve.io/s3-region: ""
    serving.kserve.io/s3-usehttps: "1"
    serving.kserve.io/s3-verifyssl: "0"
#    serving.kserve.io/s3-cabundle: "/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt"
#    serving.kserve.io/s3-cabundle-configmap: "service-ca"
  name: storage-config
  namespace: edge-ai-app
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "minio"
  AWS_SECRET_ACCESS_KEY: "minio123"
