FROM registry.access.redhat.com/ubi9/ubi-minimal:9.5

RUN microdnf install -y python3.12 python3.12-pip && \
    microdnf clean all && \
    pip3.12 install flask gunicorn minio requests


WORKDIR /app
COPY app.py /app/
COPY minio_webhook_enable.py minio_webhook_disable.py /app/
COPY gunicorn_config.py /app/

USER 1000

EXPOSE 8080

CMD ["gunicorn", "--config", "gunicorn_config.py", "app:app"]
