---
kind: Secret
apiVersion: v1
metadata:
  name: minio-credentials
stringData:
  minioRootUsername: minio
  minioRootPassword: minio123
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: minio-webhook-config
data:
  bucketName: mybucket
  pipelineEndpoint: "http://ds-pipeline-md-pipeline-server.at-test.svc.cluster.local:8888"
  pipelineName: mypipeline
  minioWebhookEndpoint_mybucket: "https://minio-webhook.myspace.svc.cluster.local:8443/minio-webhook"
