---
apiVersion: datasciencepipelinesapplications.opendatahub.io/v1
kind: DataSciencePipelinesApplication
metadata:
  name: pipeline-server
spec:
  apiServer:
    managedPipelines:
      instructLab:
        state: Removed
    resources:
      limits:
        cpu: 1
        memory: 1Gi
  dspVersion: v2
  objectStorage:
    externalStorage:
      bucket: 'pipelines'
      host: 'minio.{{ .Release.Namespace }}.svc.cluster.local'
      port: '{{ .Values.minio.services.api.port }}'
      s3CredentialsSecret:
        accessKey: username
        secretKey: password
        secretName: pipeline-bucket-minio-bucket
      scheme: https
  persistenceAgent:
    numWorkers: 1
