---
kind: ConfigMap
apiVersion: v1
metadata:
  name: minio-webhook-config
  namespace: minio
data:
  bucketName: ingest
  minioWebhookEndpoint_ingest: "http://yolo-transformer.edge-ai-app.svc/v1/models/yolo:predict"
