---
kind: ConfigMap
apiVersion: v1
metadata:
  name: minio-webhook-config
  namespace: minio
data:
  bucketName: mybucket
  pipelineEndpoint: "http://ds-pipeline-md-pipeline-server.at-test.svc.cluster.local:8888"
  pipelineName: mypipeline
  minioWebhookEndpoint_mybucket: "https://minio-webhook.myspace.svc.cluster.local:8443/minio-webhook"
