---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minio-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.minio.size}}
  volumeMode: Filesystem
