---
kind: Service
apiVersion: v1
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: minio-tls
  name: minio
spec:
  ipFamilies:
    - IPv4
  ports:
    {{- range .Values.minio.services }}
    - name: {{ . }}
      protocol: TCP
      port: {{ .port }}
      targetPort: {{ .port }}
    {{- end }}
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: minio
