FROM registry.access.redhat.com/ubi9/ubi-minimal:9.5

RUN microdnf install -y python3.12 python3.12-pip && \
    microdnf clean all

COPY requirements.txt /tmp/requirements.txt
RUN pip3.12 install --no-cache-dir --extra-index-url https://download.pytorch.org/whl/cpu -r /tmp/requirements.txt && \
    rm /tmp/requirements.txt

WORKDIR /opt/app-root

COPY model.py .
COPY simple.py .
COPY minio_webhook_disable.py /app/minio_webhook_disable.py
COPY minio_webhook_enable.py /app/minio_webhook_enable.py

USER 1000

ENTRYPOINT ["/usr/bin/python3.12", "-m", "model"]
